# Generated by Django 5.0.2 on 2024-02-15 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('bulim_id', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ish_Turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('ish_id', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('mahsulot_id', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='missed_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Xatolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('xato_id', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=10)),
                ('photo', models.ImageField(upload_to='xodim_photo/')),
                ('phone', models.CharField(max_length=15)),
                ('id_raqam', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Missed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xato_soni', models.PositiveIntegerField(null=True)),
                ('butun_soni', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('izoh', models.TextField()),
                ('ish_vaqti', models.PositiveIntegerField(null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='missed_audio/')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_mahsulot', to='Post.mahsulot')),
            ],
        ),
    ]
