# Generated by Django 5.0.2 on 2024-02-21 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_bulim_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missed',
            old_name='audio',
            new_name='golosovoy',
        ),
    ]
